# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-24 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartinfo',
            name='good',
            field=models.ForeignKey(db_column='good_id', on_delete=django.db.models.deletion.CASCADE, to='memberapp.Goods'),
        ),
    ]
