# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-20 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20181220_1634'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='publisher',
            table=None,
        ),
    ]
